services:
    usoft.address.guzzle:
      class: GuzzleHttp\Client

    usoft.postcode.client:
      class: Usoft\PostcodeBundle\Services\AddressClient
      arguments:
          - "@usoft.address.guzzle"
          - "%postcode_api_key%"
